### ISSUE TITLE
Re-publish VMF on Steam and remove iamlupo as maintainer

### ISSUE THREAD

**Issue by rpbaptist** [Vermintide-Modders/Vermintide-Mod-Framework#43]
I am a fan of Vermintide and like a lot of players use VMF and mods depending on it

Currently Iamlupo is the publisher of VMF on Steam Workshops and a maintainer of this group. Through recent actions it has become obvious he does not have the best interests of the community at heart, even leading to a stickied post and dedicated subreddit: https://ft.reddit.com/r/Vermintide/comments/ap4miv/introducing_rvermintides_book_of_grudges/

Considering he enjoys grieving the community, he could remove VMF from Steam Workshop or publish harmful code which would result in breaking mods.

I request and urge you to consider removing his influence and publishing VMF through another Steam account.

Edit: I was under the wrong assumption he was the publisher of VMW, but fortunately I was wrong.

**Comment by rpbaptist** [comment]
Paging @Azumgi and @ManuelBlanc

**Comment by rpbaptist** [comment]
After looking around it seems sensible to let @Aussiemon handle VMF.

I cannot say what Lupo did or didn't do, but I don't see any code contributions either.

**Comment by Aussiemon** [comment]
The unified, rewritten VMF was created to be independent of drama in the community; so let's leave that on reddit, please?

Even though he wasn't directly involved in the coding of the rewrite, Lupo created the original VMF and acted as a resource for this project's early development. Regardless of what Lupo might have done outside of VMF, we have a strong policy of crediting all our contributors.

Regarding your questions about his contributor permissions:

- All code changes to this repository go through @Azumgi and / or myself
- The workshop items for VMF are "owned" by @Azumgi's Steam account, and workshop contributors can't directly update or remove items they don't own.
- Fatshark employees review the updated code of sanctioned mods before they can be used in the official realm.

Hopefully this addresses your concerns. I'm closing the issue for now.
