### ISSUE TITLE
Incorrect UI Scaling

### ISSUE THREAD

**Issue by danreeves** [Vermintide-Modders/Vermintide-Mod-Framework#46]
Chat command suggestions are bigger than the chat box.

4k resolution with UI scaling set to 70

![20190228233452_1](https://user-images.githubusercontent.com/1973559/53610985-d6824080-3bc4-11e9-9130-817829e96f48.jpg)

**Comment by Dreomite** [comment]
Fixed in https://github.com/Vermintide-Mod-Framework/Vermintide-Mod-Framework/commit/09245cda2424a4b2af5a0a1b6a828484a643cf38.
![20190415124912_1](https://user-images.githubusercontent.com/35058624/56123675-9660fc80-5f7d-11e9-86d3-730c7895adb1.jpg)
