### ISSUE TITLE
Vermintide 2 v1.6 - The dev console crash the game

### ISSUE THREAD

**Issue by ScrappyCocco** [Vermintide-Modders/Vermintide-Mod-Framework#47]
Launch the modded realm with VMF enabled, and the game will crash

### Console log:
[console-2019-03-09-09.32.32-7c288e5a-3159-414d-a148-fb702a35f9de.log](https://github.com/Vermintide-Mod-Framework/Vermintide-Mod-Framework/files/2948279/console-2019-03-09-09.32.32-7c288e5a-3159-414d-a148-fb702a35f9de.log)

**Comment by Dreomite** [comment]
Even though, this was fixed in https://github.com/Vermintide-Mod-Framework/Vermintide-Mod-Framework/commit/f28fd3672ea707435f423f7f2b07b9ccf2c5fccc, Fatshark fixed the initial problem on their side, so all the changes need to be reverted. I'll get to it soon.
